const D=window.COURSE_DATA; const params=new URLSearchParams(location.search); const id=params.get('id'); const L=D.lessons.find(x=>x.id===id)||D.optional.find(x=>x.id===id);
const deck=document.querySelector('#deck'); let i=0;
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function slide(title,body,note=''){return `<section class="slide"><div class="slidecontent"><h2>${title}</h2>${body}${note?`<div class="teacher"><b>Teacher note:</b> ${note}</div>`:''}</div></section>`}
function cards(items){return `<div class="cards">${items.map((x,k)=>`<div class="card"><h3>${k+1}</h3><p>${esc(x)}</p></div>`).join('')}</div>`}
function resources(rs){return `<div class="resources-grid">${(rs||[]).map(r=>`<div class="resourcecard"><span class="kind">${esc(r.kind)}</span><p><a target="_blank" rel="noopener" href="${r.url}">${esc(r.label)}</a></p></div>`).join('')}</div>`}
function buildLesson(l){const s=[];const currentIndex=D.lessons.findIndex(x=>x.id===l.id);const prev=currentIndex>0?D.lessons[currentIndex-1]:null;s.push(`<section class="slide active"><div class="slidecontent"><p class="lesson-meta">Week ${l.week||'Optional'} • ${esc(l.sessionInWeek||'Enrichment')} • ${esc(l.apTopic)}</p><h1>${esc(l.title)}</h1><p class="big muted">${esc(l.subtitle||'')}</p><div class="teacher"><b>Teacher note:</b> Start by checking the previous work before explaining anything new.</div></div></section>`);
 if(prev){const prevTask=prev.homework||'Review the previous session and bring one question or uncertainty.';s.push(slide('Previous Work Recap',`<p class="lesson-meta">From: ${esc(prev.title)}</p><div class="card"><p>${esc(prevTask)}</p></div><div class="cards"><div class="card"><h3>Show</h3><p>Show what you wrote, coded, traced, or changed.</p></div><div class="card"><h3>Explain</h3><p>What did you expect, and why?</p></div><div class="card"><h3>Repair</h3><p>What was confusing or did not work yet?</p></div></div>`,'Treat this as a diagnostic conversation. If the previous homework exposes a misconception, repair that misconception before moving on.'));}
 s.push(slide('Retrieval Warm-Up',`<p class="q">Without notes: what idea from the previous lesson could help with today’s topic?</p><p class="muted">Give a specific example, not only a vocabulary word.</p>`,'Use the first 3–5 minutes diagnostically. If the prior mental model is weak, repair it before adding new detail.'));
 s.push(slide('Today’s Mental Model',`<p class="big">${esc(l.model)}</p><div class="flow"><div class="node">Understand</div><div class="arrow">→</div><div class="node">Predict</div><div class="arrow">→</div><div class="node">Build</div><div class="arrow">→</div><div class="node">Test</div></div>`,'Keep the mental model short enough that Oscar can restate it in his own words.'));
 s.push(slide('Core Ideas',cards(l.points||[]),'Ask “why?” after each point. The goal is causal understanding, not recitation.'));
 if(l.code) s.push(slide('Read the Example First',`<pre class="code">${esc(l.code)}</pre><p class="q">Predict what this code or model does before running or explaining it.</p>`,'Have Oscar annotate values, receivers, indexes, or loop state directly on paper.'));
 s.push(slide('Think',`<p class="q">${esc(l.think)}</p><button class="revealbtn" onclick="this.nextElementSibling.classList.toggle('show')">Show discussion move</button><div class="reveal card"><p>Explain your answer using the program state, the specification, or a concrete test case. If uncertain, choose a tiny example and trace it.</p></div>`,'Do not reveal immediately. Ask for a prediction and the reason behind it.'));
 s.push(slide('Hands-On Activity',`<div class="card"><p class="big">${esc(l.activity)}</p></div><div class="flow"><div class="node">Predict</div><div class="arrow">→</div><div class="node">Run / Trace</div><div class="arrow">→</div><div class="node">Explain</div><div class="arrow">→</div><div class="node">Modify</div></div>`,'Oscar should do the typing/tracing. Give hints before code.'));
 s.push(slide('AP Connection',`<div class="card"><p>${esc(l.apConnection||'This lesson supports current AP CSA computational thinking and code reasoning.')}</p></div><p class="muted">Practice both reading code and writing code. The exam asks for both.</p>`,'Use AP wording naturally, but do not let exam vocabulary replace the underlying concept.'));
 s.push(slide('Free Resources',resources(l.resources),'Resources are optional reinforcement. Prefer the current-framework materials; older videos are explicitly labeled.'));
 s.push(slide('Exit Check',cards([`Explain today’s mental model without using the slide.`,`Give one example and one non-example or common mistake.`,`What would you test to know your code is correct?`]),'If Oscar cannot explain one of these, record it for the next lesson retrieval.'));
 s.push(slide('Homework',`<div class="card"><p class="big">${esc(l.homework)}</p></div><p class="muted">Keep it small enough to complete consistently.</p>`,'The next lesson should begin by checking this work, not by immediately introducing new material.'));
 return s.join('');}
function buildPractice(l){const cover=l.covers||[];const s=[];s.push(`<section class="slide active"><div class="slidecontent"><p class="lesson-meta">Week ${l.week} • Practice</p><h1>${esc(l.title)}</h1><p class="big muted">${esc(l.subtitle||'')}</p><div class="teacher"><b>Teacher note:</b> This is a diagnostic session. Record patterns of hesitation; do not turn every missed item into a long lecture.</div></div></section>`);
 s.push(slide('Retrieval — No Notes',cards(cover.map(x=>`Explain the key idea from: ${x}`)),'Ask for examples and reasoning. Vocabulary-only answers are not enough.'));
 s.push(slide('Trace',`<p class="q">Choose one code example from the covered lessons. Predict every important variable value or output before running it.</p><div class="flow"><div class="node">Read</div><div class="arrow">→</div><div class="node">Trace</div><div class="arrow">→</div><div class="node">Commit</div><div class="arrow">→</div><div class="node">Run</div></div>`,'Have Oscar use a trace table.'));
 s.push(slide('Debug',`<p class="q">Intentionally introduce one syntax/compile error or logic error into a recent program. Can you diagnose it from evidence?</p><div class="card"><p>Expected → Actual → Error message / trace → Cause → Smallest fix</p></div>`,'Ask him to name the error category before fixing it.'));
 s.push(slide('Write',`<p class="q">Rebuild one small solution from a specification without looking at the previous code.</p><p class="muted">Say the algorithm in English first.</p>`,'Do not provide a complete solution before an attempt.'));
 s.push(slide('AP-Style Reasoning',`<div class="cards"><div class="card"><h3>Predict</h3><p>What result does the code produce?</p></div><div class="card"><h3>Correct</h3><p>Why would this code fail to compile or behave incorrectly?</p></div><div class="card"><h3>Design</h3><p>Which code segment best matches the specification?</p></div></div>`,'Use original questions or secure AP Classroom questions only when you have legitimate access.'));
 s.push(slide('Error Log',`<div class="card"><p>For every miss:</p><ol><li>What was being tested?</li><li>What did I think?</li><li>Why was that wrong?</li><li>Concept / reading / Java / algorithm / time?</li><li>What rule or mental model fixes it?</li></ol></div>`,'One good error-log entry is more valuable than ten rushed questions.'));
 s.push(slide('Resources',resources(l.resources),'Use resources after the attempt, not as a replacement for attempting the problem.'));
 s.push(slide('Exit Check',cards(['What was strongest today?','What mistake repeated?','What should the next lesson retrieve first?']),'Record one specific weak point for next time.'));
 return s.join('');}
if(!L){deck.innerHTML='<section class="slide active"><div class="slidecontent"><h1>Lesson not found</h1><p><a href="index.html">Return to course</a></p></div></section>';}else{document.title=L.title+' • Oscar AP CSA';deck.innerHTML=L.kind==='practice'?buildPractice(L):buildLesson(L);}
const slides=[...document.querySelectorAll('.slide')];function render(){slides.forEach((s,j)=>s.classList.toggle('active',j===i));document.querySelector('#counter').textContent=`${i+1} / ${slides.length}`;}function next(){if(i<slides.length-1){i++;render();}}function prev(){if(i>0){i--;render();}}
document.querySelector('#nextBtn').onclick=next;document.querySelector('#backBtn').onclick=prev;document.querySelector('#notesBtn').onclick=()=>document.body.classList.toggle('show-notes');document.querySelector('#fullBtn').onclick=()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.();};document.addEventListener('keydown',e=>{if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();next();}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();prev();}if(e.key.toLowerCase()==='n')document.body.classList.toggle('show-notes');if(e.key.toLowerCase()==='f'){if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.();}});render();